import { test, expect } from '@playwright/test'
import fs from 'node:fs/promises'

for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
  test(`research lifecycle and catalog at ${viewport.width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize(viewport)
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/institutional')
    await expect(page.getByRole('heading', { name: 'Sign in to MR Bot' })).toBeVisible()
    await page.getByLabel('Access key').fill('visual-test-admin-key-0000000000000000')
    await page.getByRole('button', { name: 'Sign in', exact: true }).click()
    await page.getByRole('button', { name: 'Order lifecycle simulator', exact: true }).click()
    const editor = page.getByRole('textbox', { name: 'Scenario JSON', exact: true })
    const original = await editor.inputValue()
    await editor.fill('{bad')
    await page.getByRole('button', { name: 'Run offline analysis', exact: true }).click()
    await expect(page.getByRole('alert')).toBeVisible()
    await editor.fill(original)
    await page.getByRole('button', { name: 'Run offline analysis', exact: true }).click()
    const report = page.getByLabel('Order lifecycle results')
    await expect(report).toBeVisible()
    await expect(report.getByLabel('Client acknowledgement state')).toContainText('Known inventory: 0')
    await expect(report.getByLabel('Client acknowledgement state')).toContainText('Pending fill acknowledgements: 1')
    await expect(page.getByLabel('Exit cost projection')).toContainText('Projection status: blocked')
    await expect(report.getByLabel('Orders table').getByRole('cell', { name: 'venue rejected', exact: true })).toBeVisible()
    await report.evaluate(el => el.scrollIntoView({ block: 'start' }))
    await page.screenshot({ path: testInfo.outputPath('lifecycle.png') })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    expect(await page.locator('main').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    const downloaded = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Download reproducible report' }).click()
    const download = await downloaded
    const body = JSON.parse(await fs.readFile((await download.path())!, 'utf8'))
    expect(body.operation).toBe('order-lifecycle')
    expect(body.live_authorized).toBe(false)
    expect(body.result.client_inventory).toBe('0')
    expect(body.result.ending_inventory).toBe('1')
    expect(body.result.pending_fill_acknowledgements).toBe(1)
    await page.getByRole('button', { name: 'Automatic quoting', exact: true }).click()
    await page.getByRole('button', { name: 'Run offline analysis', exact: true }).click()
    await expect(page.getByLabel('Quote decisions table')).toBeVisible()
    await expect(page.getByLabel('Quote decisions table').getByRole('cell', { name: 'expiry', exact: true })).toBeVisible()
    await expect(page.getByLabel('Quote decisions table').getByRole('columnheader', { name: 'Expiry (ms)' })).toBeVisible()
    await expect(page.getByLabel('Event audit table').getByRole('cell', { name: 'client disconnected', exact: true })).toBeVisible()
    await expect(page.getByLabel('Client acknowledgement state')).toContainText('Order connection: Connected')
    await expect(page.getByLabel('Fills table').getByRole('columnheader', { name: 'Delivered (ms)' })).toBeVisible()
    await expect(page.getByLabel('Exit cost projection')).toContainText('Projection status: complete')
    await page.getByLabel('Order lifecycle results').evaluate(el => el.scrollIntoView({ block: 'start' }))
    await page.screenshot({ path: testInfo.outputPath('auto-quoting.png') })
    expect(await page.locator('main').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await page.getByRole('link', { name: 'Instrument catalog' }).click()
    await page.getByRole('button', { name: 'Register revision', exact: true }).click()
    await expect(page.getByRole('status')).toContainText('Revision registered')
    await page.getByRole('button', { name: 'Generate offline plan' }).click()
    await expect(page.getByRole('heading', { name: 'Instrument execution plan' })).toBeVisible()
    await page.getByRole('heading', { name: 'Instrument catalog', exact: true }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: testInfo.outputPath('catalog.png') })
    expect(await page.locator('main').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await page.getByRole('button', { name: 'Sign out' }).click()
    await expect(page.getByRole('heading', { name: 'Sign in to MR Bot' })).toBeVisible()
    expect(errors).toEqual([])
  })
}
