-- Supabase/PostgreSQL schema for Mean Reversion Bot.
-- Run this entire file in Supabase SQL Editor.
-- Safe to run more than once; it does not drop existing data.

create table if not exists public.trades (
    id integer generated by default as identity primary key,
    trade_id varchar(32) not null unique,
    contract_id integer,
    symbol varchar(32) not null,
    timeframe varchar(8) not null,
    direction varchar(8) not null,
    contract_type varchar(16) not null,
    instrument_type varchar(16),
    entry_price double precision not null,
    exit_price double precision,
    stop_loss double precision not null,
    take_profit double precision not null,
    stake double precision not null,
    pnl double precision,
    pnl_pct double precision,
    confluence_score integer not null default 0,
    reason_code varchar(64) not null default '',
    breakdown_json jsonb,
    z_score double precision,
    rsi_value double precision,
    bb_position varchar(16),
    vwap_dev double precision,
    stoch_k double precision,
    hurst_value double precision,
    atr_value double precision,
    lsl_wick_ratio double precision,
    status varchar(12) not null default 'pending',
    close_reason varchar(24),
    opened_at timestamp without time zone not null default (now() at time zone 'utc'),
    closed_at timestamp without time zone
);

create table if not exists public.signals (
    id integer generated by default as identity primary key,
    symbol varchar(32) not null,
    timeframe varchar(8) not null,
    direction varchar(8),
    score integer not null default 0,
    fired boolean not null default false,
    reason varchar(128) not null default '',
    z_score double precision,
    rsi double precision,
    bb_position varchar(16),
    vwap_dev_atr double precision,
    stoch_k double precision,
    hurst double precision,
    atr double precision,
    lsl_grab boolean not null default false,
    lsl_wick_ratio double precision,
    bos_choch boolean not null default false,
    order_block boolean not null default false,
    htf_aligned boolean not null default false,
    volume_ratio double precision,
    breakdown_json jsonb,
    evaluated_at timestamp without time zone not null default (now() at time zone 'utc'),
    eval_ms double precision
);

create table if not exists public.candles (
    id integer generated by default as identity primary key,
    symbol varchar(32) not null,
    timeframe integer not null,
    ts timestamp without time zone not null,
    open double precision not null,
    high double precision not null,
    low double precision not null,
    close double precision not null,
    volume double precision not null default 0,
    constraint uq_candle_symbol_tf_ts unique (symbol, timeframe, ts)
);

create table if not exists public.liquidity_zones (
    id integer generated by default as identity primary key,
    symbol varchar(32) not null,
    timeframe varchar(8) not null,
    price double precision not null,
    zone_type varchar(32) not null,
    strength double precision not null default 0.5,
    test_count integer not null default 0,
    invalidated boolean not null default false,
    first_seen timestamp without time zone not null default (now() at time zone 'utc'),
    last_tested timestamp without time zone,
    updated_at timestamp without time zone not null default (now() at time zone 'utc')
);

create table if not exists public.equity_snapshots (
    id integer generated by default as identity primary key,
    ts timestamp without time zone not null default (now() at time zone 'utc'),
    balance double precision not null,
    open_equity double precision,
    daily_pnl double precision,
    open_trades integer not null default 0,
    note varchar(64)
);

create table if not exists public.bot_events (
    id integer generated by default as identity primary key,
    event_type varchar(48) not null,
    severity varchar(12) not null default 'info',
    message text not null,
    details_json jsonb,
    ts timestamp without time zone not null default (now() at time zone 'utc')
);

create table if not exists public.config (
    id integer generated by default as identity primary key,
    key varchar(64) not null unique,
    value text not null,
    value_type varchar(12) not null default 'str',
    description varchar(256),
    updated_at timestamp without time zone not null default (now() at time zone 'utc')
);

create table if not exists public.backtest_results (
    id integer generated by default as identity primary key,
    run_id varchar(32) not null unique,
    symbol varchar(32) not null,
    timeframe varchar(8) not null,
    date_from timestamp without time zone not null,
    date_to timestamp without time zone not null,
    total_trades integer not null default 0,
    winning_trades integer not null default 0,
    losing_trades integer not null default 0,
    win_rate double precision,
    avg_rr double precision,
    profit_factor double precision,
    sharpe_ratio double precision,
    max_drawdown double precision,
    total_pnl double precision,
    total_pnl_pct double precision,
    params_json jsonb,
    equity_curve_json jsonb,
    trades_json jsonb,
    run_at timestamp without time zone not null default (now() at time zone 'utc'),
    duration_seconds double precision
);

create index if not exists ix_trades_trade_id on public.trades (trade_id);
create index if not exists ix_trades_contract_id on public.trades (contract_id);
create index if not exists ix_trades_symbol on public.trades (symbol);
create index if not exists ix_trades_status on public.trades (status);
create index if not exists ix_trades_opened_at on public.trades (opened_at);
create index if not exists ix_trades_symbol_opened on public.trades (symbol, opened_at);
create index if not exists ix_trades_status_opened on public.trades (status, opened_at);

create index if not exists ix_signals_symbol on public.signals (symbol);
create index if not exists ix_signals_fired on public.signals (fired);
create index if not exists ix_signals_evaluated_at on public.signals (evaluated_at);
create index if not exists ix_signals_symbol_evaluated on public.signals (symbol, evaluated_at);
create index if not exists ix_signals_fired_evaluated on public.signals (fired, evaluated_at);

create index if not exists ix_candles_symbol on public.candles (symbol);
create index if not exists ix_candles_ts on public.candles (ts);
create index if not exists ix_candles_symbol_tf_ts on public.candles (symbol, timeframe, ts);

create index if not exists ix_liquidity_zones_symbol on public.liquidity_zones (symbol);
create index if not exists ix_liquidity_zones_invalidated on public.liquidity_zones (invalidated);
create index if not exists ix_lz_symbol_tf_valid on public.liquidity_zones (symbol, timeframe, invalidated);

create index if not exists ix_equity_snapshots_ts on public.equity_snapshots (ts);
create index if not exists ix_bot_events_event_type on public.bot_events (event_type);
create index if not exists ix_bot_events_ts on public.bot_events (ts);
create index if not exists ix_bot_events_type_ts on public.bot_events (event_type, ts);
create index if not exists ix_bot_events_severity_ts on public.bot_events (severity, ts);
create index if not exists ix_config_key on public.config (key);
create index if not exists ix_backtest_results_run_id on public.backtest_results (run_id);
create index if not exists ix_backtest_results_run_at on public.backtest_results (run_at);

-- The API connects with the Supabase Postgres database URL directly, so
-- Row Level Security is not required for this server-to-server connection.
-- Never expose the database password or service-role key to the frontend.
